image: openjdk:17-jdk-slim

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_ROOT: "/sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  # Install required tools
  - apt-get update
  - apt-get install -y wget
  - apt-get install -y unzip

  # Create the necessary directory structure for the Android SDK
  - mkdir -p /sdk/cmdline-tools

  # Download and install Android SDK tools
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip" -O android-tools.zip
  - unzip android-tools.zip -d /sdk/cmdline-tools
  - mkdir -p /sdk/cmdline-tools/latest
  - mv /sdk/cmdline-tools/cmdline-tools/* /sdk/cmdline-tools/latest/

  # Add sdkmanager to the PATH
  - export PATH=$PATH:/sdk/cmdline-tools/latest/bin

  # Accept licenses and install SDK components
  - yes | sdkmanager --licenses || true
  - sdkmanager --update || true
  - sdkmanager --install "platforms;android-$ANDROID_COMPILE_SDK" "build-tools;$ANDROID_BUILD_TOOLS" "platform-tools" || true

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

unit_test:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    when: always
    reports:
      junit: app/build/test-results/testDebugUnitTest/TEST-*.xml