image: openjdk:17-jdk-slim

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "33.0.2"
  ANDROID_SDK_ROOT: "/sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  # Download and install Android SDK
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip" -O android-tools.zip
  - unzip android-tools.zip -d /sdk/cmdline-tools
  - mv /sdk/cmdline-tools/cmdline-tools /sdk/cmdline-tools/latest
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
  - sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-$ANDROID_COMPILE_SDK" "build-tools;$ANDROID_BUILD_TOOLS" "platform-tools"

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

unit_test:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    when: always
    reports:
      junit: app/build/test-results/testDebugUnitTest/TEST-*.xml